name: deploy
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:
  deploy:
    runs-on: macos-12

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Set Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Import iOS CodeSign Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          create-keychain: true
          keychain-password: ${{ steps.develop-certificate.outputs.keychain-password }}
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: Download Provisioning Profiles
        uses: poad/apple-provisioning-profiles-downloader@v1.0.7
        with: 
          bundle-id: 'com.github.poad.Firebase-Invistigate'
          profile-type: IOS_APP_DEVELOPMENT
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GoogleService-Info.plist.plist
        env:
          GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO }}
        run: |
          touch "Firebase Invistigate/GoogleService-Info.plist"
          echo "${GOOGLE_SERVICE_INFO_PLIST}" >> "Firebase Invistigate/GoogleService-Info.plist"
          cat "Firebase Invistigate/GoogleService-Info.plist"

      - name: Generate exportOptions.plist
        env:
          PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          touch exportOptions.plist
          echo "${PLIST}" >> exportOptions.plist
          cat exportOptions.plist

      - name: iOS app build
        uses: devbotsxyz/xcode-build@v1
        with:
          project: 'Firebase Invistigate.xcodeproj'
          scheme: 'Firebase Invistigate'
